version: '3.8'

services: 
  healthcare_go_server:
    build: .
    ports:
      - "3000"
    restart: always
    env_file:
      - .env
    networks:
      - app_network
    deploy:
      replicas: 3
    depends_on:
      - mongodb
      - rabbitmq
      - redis
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootuser
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootuser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rootuser
      RABBITMQ_DEFAULT_PASS: rootuser
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - healthcare_go_server
    networks:
      - app_network

volumes:
  mongodb_data:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  redis-data:
    driver: local 

networks:
  app_network:
    driver: bridge
