version: '3.8'

services: 
  healthcare_go_server:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootuser
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootuser
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rootuser
      RABBITMQ_DEFAULT_PASS: rootuser
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb_data:
  postgres_data:

  rabbitmq_data:
  rabbitmq_logs:

  redis-data:
    driver: local 